# Generated by Django 4.1 on 2023-02-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuesEso',
            new_name='SEIA',
        ),
    ]
