# Generated by Django 4.1 on 2023-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0003_alter_seia_estado_alter_seia_region_alter_seia_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seia',
            name='estado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seia',
            name='region',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seia',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seia',
            name='tipologia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seia',
            name='titular',
            field=models.CharField(max_length=200),
        ),
    ]
