# Generated by Django 4.1 on 2023-02-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0004_alter_seia_estado_alter_seia_region_alter_seia_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seia',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
